name: Maven Security Scan Daily

on:
  workflow_dispatch:
  # Trigger the workflow at 00:00:00 of Germany time (runner is UTC time, UTC+2 or UTC+1 depending on daylight saving)
  schedule:
    - cron: '0 23 * * *'

jobs:
  fetch-branches:
    name: Fetch Branches for Security Scan
    runs-on: [self-hosted]

    outputs:
      branch_matrix: ${{ steps.set_branch.outputs.branch_matrix }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Fetch all branches
        id: fetch_branches
        run: |
          git fetch --all
          BRANCHES=$(git branch -r | grep "origin/release/" | sed 's/origin\///' | sort -Vr)
          echo "RELEASE_BRANCHES=$(echo $BRANCHES | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Define matrix branches
        id: set_branch
        run: |
          if [ -z "$RELEASE_BRANCHES" ]; then
            echo '["main", "develop"]' > branch_matrix.json
          else
            RELEASE_BRANCHES_JSON=$(echo $RELEASE_BRANCHES | sed 's/ /", "/g')
            echo '["main", "develop", "'$RELEASE_BRANCHES_JSON'"]' > branch_matrix.json
          fi
          cat branch_matrix.json
          echo "branch_matrix=$(cat branch_matrix.json)" >> $GITHUB_OUTPUT

  security-scan-per-branch:
    needs: fetch-branches
    runs-on: [self-hosted]
    strategy:
      matrix:
        branch: ${{ fromJson(needs.fetch-branches.outputs.branch_matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set BlackDuck Phase
        run: |
          echo "Matrix branch is: ${{ matrix.branch }}"

          if [[ "${{ matrix.branch }}" == "main" ]]; then
            BLACKDUCK_PHASE="RELEASED"
            SONAR_BRANCH="main"
            SECHUB_BRANCH="main"
          elif [[ "${{ matrix.branch }}" == "develop" ]]; then
            BLACKDUCK_PHASE="DEVELOPMENT"
            SONAR_BRANCH="develop"
            SECHUB_BRANCH="develop"
          elif [[ "${{ matrix.branch }}" == release/* ]]; then
            BLACKDUCK_PHASE="PRERELEASE"
            SONAR_BRANCH="release"
            SECHUB_BRANCH="release"
          else
            BLACKDUCK_PHASE="DEVELOPMENT"
            SONAR_BRANCH="develop"
            SECHUB_BRANCH="develop"
          fi

          echo "BLACKDUCK_PHASE=$BLACKDUCK_PHASE" >> $GITHUB_ENV
          echo "SONAR_BRANCH=$SONAR_BRANCH" >> $GITHUB_ENV
          echo "SECHUB_BRANCH=$SECHUB_BRANCH" >> $GITHUB_ENV
          echo "BLACKDUCK_PHASE value is: $BLACKDUCK_PHASE"
          echo "SONAR_BRANCH value is: $SONAR_BRANCH"
          echo "SECHUB_BRANCH value is: $SECHUB_BRANCH"

      - name: Maven Test with Security Scanning
        uses: ms-vsm/reusable-workflow/.github/workflows/maven-test-with-security-scanning.yml@main
        with:
          git_branch: ${{ matrix.branch }}
          service_name: vsm-stock-api
          sonar_branch: ${{ env.SONAR_BRANCH }}
          blackduck_project_name: VSM_STM_API
          blackduck_rapid_scan: 'false'
          blackduck_phase: ${{ env.BLACKDUCK_PHASE }}
          blackduck_project_version: ${{ env.BLACKDUCK_PHASE }}
          setup_local_database: 'true'
          sechub_branch: ${{ env.SECHUB_BRANCH }}
