name: Maven Security Scan Daily

on:
  workflow_dispatch:
  # Trigger the workflow at 00:00:00 of Germany time (runner is UTC time, UTC+2 or UTC+1 depending on daylight saving)
  schedule:
    - cron: '0 23 * * *'

jobs:
  fetch-branches:
    name: Fetch Branches for Security Scan
    runs-on: [self-hosted]

    outputs:
      branch_matrix: ${{ steps.set_branch.outputs.branch_matrix }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Fetch all branches
        id: fetch_branches
        run: |
          git fetch --all
          BRANCHES=$(git branch -r | grep "origin/release/" | sed 's/origin\///' | sort -Vr)
          echo "RELEASE_BRANCHES=$(echo $BRANCHES | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Define matrix branches
        id: set_branch
        run: |
          if [ -z "$RELEASE_BRANCHES" ]; then
            echo '["main", "develop"]' > branch_matrix.json
          else
            RELEASE_BRANCHES_JSON=$(echo $RELEASE_BRANCHES | sed 's/ /", "/g')
            echo '["main", "develop", "'$RELEASE_BRANCHES_JSON'"]' > branch_matrix.json
          fi
          cat branch_matrix.json
          echo "branch_matrix=$(cat branch_matrix.json)" >> $GITHUB_OUTPUT

  security-scan-per-branch:
    needs: fetch-branches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.fetch-branches.outputs.branch_matrix) }}
    uses: sancheam/reusable-workflow/.github/workflows/maven-test-with-security-scanning.yml@main
    secrets: inherit
    with:
      git_branch: ${{ matrix.branch }} 
      service_name: vsm-stock-api
      sonar_branch: |
        ${{ github.event.inputs.sonar_branch || (matrix.branch == 'main' && 'main') || (matrix.branch == 'develop' && 'develop') || (startsWith(matrix.branch, 'release/') && 'release') || 'develop' }}
      blackduck_project_name: VSM_STM_API
      blackduck_rapid_scan: 'false'
      blackduck_phase: |
        ${{ github.event.inputs.blackduck_phase || (matrix.branch == 'main' && 'RELEASED') || (matrix.branch == 'develop' && 'DEVELOPMENT') || (startsWith(matrix.branch, 'release/') && 'PRERELEASE') || 'DEVELOPMENT' }}
      blackduck_project_version: |
        ${{ github.event.inputs.blackduck_phase || (matrix.branch == 'main' && 'RELEASED') || (matrix.branch == 'develop' && 'DEVELOPMENT') || 'PRERELEASE' }}
      setup_local_database: 'true'
      sechub_branch: |
        ${{ github.event.inputs.sechub_branch || (matrix.branch == 'main' && 'main') || (matrix.branch == 'develop' && 'develop') || (startsWith(matrix.branch, 'release/') && 'release') || 'develop' }}
